### PR TITLE
:love_hotel:restructure files:love_hotel:

### PR DESCRIPTION
**Pull request by spences10**
Move all the files ready for ribUI

@mattpalermo please could you review and merge, or sign off and I'll merge on or t'other :+1: 

Just saw all the work you have put in on the missing references and items missing on the `.conf` file, impressive +:100:

### CODE REVIEW

**Comment by mattpalermo** [comment]
Nice, makes the project directory very neat. Thankyou. Just one change before merging, I think the build instructions in the README should ever so slightly updated to show that the files are now in the src directory. I'll do a tiny commit to the restructure branch and then I think it's all good +1.

**Comment by mattpalermo** [comment]
Also, should this be merged to dev instead of master? I always get confused about the dev / master branch situation.

**Review by mattpalermo — APPROVED** [review]

**Comment by spences10** [comment]
I'm going to say merge with master and `dev` can `do one` because it's confusing us both, ok?

**Comment by mattpalermo** [comment]
Sounds good.

**Pull request merged**
