### PR TITLE
Convert config file to JSON format

### PR DESCRIPTION
**Pull request by mattpalermo**
Using the VBA-JSON library, the config file is now using JSON. This has simplified the task of serializing the configuration data. No need to worry about escaping anything, parsing complex structure or handling many different styles of whitespace.

While I was doing this I some changes to how the import and export is done but functionally it should be the same.

The new "Module Paths" configuration property gives a mapping from modules to file paths. These file paths may be either relative or absolute. However I have not done any testing of this beyond the default (all files in the same directory).

The addition of more configuration is now a piece of cake. Simply add more properties to the configuration object.

This branch (json) is based on my housecleaning branch which was submitted for a PR in #9 .

### CODE REVIEW

**Comment by spences10** [comment]
Couple of things mate.

image

Looks like the module properties are getting into the project here ⬆️ 

So remove them and try compile the project and get the following ⬇️ 

image

Can you resolve these?

Thanks

**Comment by mattpalermo** [comment]
Hmm, strange. So the problem is that Dictionary.cls is being imported as a standard module instead of a class module. How are you importing the modules? Are you manually importing them? The config file has been changed to Json format as well so you won't be able to use a previous version of the add-in to automatically import the modules.

**Comment by spences10** [comment]
I opened the VBA-IDE-Code-Export.xlsm, dragged and dropped the component into the VBA IDE, is that not how you want to do it now?

**Comment by mattpalermo** [comment]
That should work. What version of Excel are you using?

**Comment by spences10** [comment]
I use office 360

**Comment by mattpalermo** [comment]
I found the following issue with another bit of code made my timhall: https://github.com/VBA-tools/VBA-Web/issues/24

It seems like exactly the same thing that is happening with Dictionary (which was written by timhall)

**Comment by mattpalermo** [comment]
Here is the issue for this exact library https://github.com/VBA-tools/VBA-Dictionary/issues/5#issuecomment-77081615

It seems to be a problem with line endings. A quick solution is not to use the Dictionary from VBA-Dictionary and instead use the Dictionary from the Microsoft scripting library. They are interchangable.

**Comment by mattpalermo** [comment]
Ok I think I have fixed the problem. Give it a shot to see if it works now.

**Comment by spences10** [comment]
No still not able to import the class, I tried drag and drop and the manual process same with #11

**Comment by mattpalermo** [comment]
Make sure you are fetching and checking out the latest version of the branch from github. I have removed the Dictionary.cls completely. Unless you are now having troubles with the other class?

**Pull request merged**
