### PR TITLE
Remove unnecessary configuration and global state usage

### PR DESCRIPTION
**Pull request by mattpalermo**
See issues #4 and #5. 

Only the config file is used for storing the file list now. Additionally the ImportTo and ExportFrom configuration was removed. This allowed me to remove the configuration dialog and remove the dependency on system wide shared state.

Note that the ImportTo and ExportFrom feature was removed since it didn't support relative path names. By removing it, we obtain a simple, working implementation. We can add these features back when the time comes to implementing it.

### CODE REVIEW

**Comment by spences10** [comment]
@mattpalermo I've just gone to review this and got in a bit of a mess :confused: , which branches relate to this PR please?

Just some other things to note, when trying to make the project I found that all the modules were already in the binary so I had to remove them all and start again, the frmConfigure.frm couldn't be imported for some reason either.

**Comment by mattpalermo** [comment]
The noconfig branch contains the changes relating to simplifying / removing the configuration and removing the dependence on global state.

Make sure that you checkout the branch properly with a clean working directory. In this branch, there is no binary. The instructions to build the binary can be found in the README. 

The next pull request is for the self-use branch. It builds on changes made in the noconfig branch. The changes made in this branch simplifies the build process by including a template binary and a configuration file for using a copy of this add-in to automatically import the files into the template.

I intended for you to look at this pull request first and then the other pull request if this one is accepted.

**Comment by mattpalermo** [comment]
Here is a link to my noconfig branch on github https://github.com/mattpalermo/VBA-IDE-Code-Export/tree/noconfig

**Comment by spences10** [comment]
Just so we're clear:

 1. noconfig is the one you want me to look at first
 2. self-use is to be looked at after noconfig has been merged

Thanks :smile:

**Comment by mattpalermo** [comment]
That's right :)

**Pull request merged**
