### PR TITLE
:roller_coaster:add gifs yo!:roller_coaster:

### PR DESCRIPTION
**Pull request by spences10**

### CODE REVIEW

**Comment by spences10** [comment]
Added some gif for instructions @mattpalermo

**Review by mattpalermo — APPROVED** [review]
Nice gifs yo!

For the creation of the zip, maybe we could mention that you just have to "create a zip with the contents of the VBA-IDE-Code-Export.package folder" and this gif shows you a way of achieving this.

I have a few thoughts about tweaks to your work on the README but since it applies to more than just this change I think I'll post it on the Issues list for discussion. E.g. I think the Usage section needs to go above the Build section because hopefully most users won't need to go through the build process.

**Comment by spences10** [comment]
I forgot to ask @mattpalermo are you able to make a release for this? Please :smile:

**Comment by mattpalermo** [comment]
@spences10 Will do :)

**Pull request merged**
